CREATE WAREHOUSE IF NOT EXISTS SALES_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SALES_WH;
CREATE DATABASE IF NOT EXISTS CUSTOMER_SALES_DB;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_SALES_DB.SALES_SCHEMA;

USE DATABASE CUSTOMER_SALES_DB;
USE SCHEMA SALES_SCHEMA;

CREATE FILE FORMAT IF NOT EXISTS SALES_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS SALES_STAGE
FILE_FORMAT = SALES_CSV_FORMAT;

SHOW STAGES;
CREATE TABLE CUSTOMERS (
    customer_id INTEGER,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(100)
);
CREATE TABLE FOODITEMS (
    food_id INTEGER,
    name VARCHAR(100),
    price NUMBER(10,2),
    category VARCHAR(50),
    availability VARCHAR(20)
);
CREATE TABLE ORDERS (
    order_id INTEGER,
    customer_id INTEGER,
    food_id INTEGER,
    quantity INTEGER,
    order_date TIMESTAMP_NTZ,
    status VARCHAR(30),
    total_amount NUMBER(10,2)
);
COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = (
    FORMAT_NAME = SALES_CSV_FORMAT
);
COPY INTO FOODITEMS
FROM @SALES_STAGE/fooditems.csv
FILE_FORMAT = (
    FORMAT_NAME = SALES_CSV_FORMAT
);
COPY INTO ORDERS
FROM @SALES_STAGE/orders.csv
FILE_FORMAT = (
    FORMAT_NAME = SALES_CSV_FORMAT
);

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(o.total_amount) AS total_spent
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spent DESC;

SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY TOTAL_AMOUNT_SPENT DESC
LIMIT 1;

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE
FROM ORDERS
WHERE STATUS = 'Delivered';

SELECT
    f.CATEGORY AS FOOD_CATEGORY,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FOODITEMS f
JOIN ORDERS o
    ON f.FOOD_ID = o.FOOD_ID
GROUP BY f.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    STATUS,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY STATUS
ORDER BY TOTAL_REVENUE DESC;

SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY TOTAL_AMOUNT_SPENT DESC
LIMIT 3;

CREATE OR REPLACE VIEW CUSTOMER_SALES_REPORT AS
SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME;

SELECT *
FROM CUSTOMER_SALES_REPORT;

SELECT *
FROM CUSTOMER_SALES_REPORT
ORDER BY TOTAL_AMOUNT_SPENT DESC;

select c.customer_id,c.first_name,count(o.order_date)
from customers c
join orders o
join fooditems f
on f.food_id = o.food_id
on c.customer_id=o.customer_id
where o.total_amount>100
group by c.customer_id,c.first_name
having count(*)>2;
