CREATE WAREHOUSE IF NOT EXISTS CUSTOMER_MDM_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE CUSTOMER_MDM_WH;

CREATE DATABASE IF NOT EXISTS CUSTOMER_MDM_DB;
USE DATABASE CUSTOMER_MDM_DB;

CREATE SCHEMA IF NOT EXISTS CUSTOMER_MDM_SCHEMA;
USE SCHEMA CUSTOMER_MDM_SCHEMA;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE CUSTOMERS_INITIAL_STAGE
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);
CREATE OR REPLACE TABLE CUSTOMER_UPDATES_STAGE
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE
);
COPY INTO CUSTOMERS_INITIAL_STAGE
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = (
    FORMAT_NAME = CUSTOMER_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CUSTOMER_UPDATES_STAGE
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (
    FORMAT_NAME = CUSTOMER_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE CUSTOMER_HYBRID_DIM
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    CUSTOMER_ID NUMBER NOT NULL,

    CUSTOMER_NAME VARCHAR(100),

    CITY VARCHAR(100),

    PREVIOUS_CITY VARCHAR(100),

    STATE VARCHAR(100),

    CURRENT_MEMBERSHIP VARCHAR(50),

    PREVIOUS_MEMBERSHIP VARCHAR(50),

    HISTORICAL_MEMBERSHIP VARCHAR(50),

    SEGMENT VARCHAR(50),

    EFFECTIVE_DATE DATE,

    EXPIRY_DATE DATE,

    IS_CURRENT BOOLEAN
);

INSERT INTO CUSTOMER_HYBRID_DIM
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE AS EFFECTIVE_DATE,
    '9999-12-31'::DATE AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM CUSTOMERS_INITIAL_STAGE;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM CUSTOMER_HYBRID_DIM;

SELECT COUNT(*) AS CURRENT_RECORDS
FROM CUSTOMER_HYBRID_DIM
WHERE IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_HYBRID_DIM
ORDER BY CUSTOMER_ID;

UPDATE CUSTOMER_HYBRID_DIM D
SET
    EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        U.EFFECTIVE_DATE
    ),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES_STAGE U
WHERE D.CUSTOMER_ID = U.CUSTOMER_ID
  AND D.IS_CURRENT = TRUE;

INSERT INTO CUSTOMER_HYBRID_DIM
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,

    U.CUSTOMER_NAME,

    U.CITY,

    OLD.CITY AS PREVIOUS_CITY,

    U.STATE,

    U.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    OLD.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    U.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    U.SEGMENT,

    U.EFFECTIVE_DATE,

    '9999-12-31'::DATE AS EXPIRY_DATE,

    TRUE AS IS_CURRENT

FROM CUSTOMER_UPDATES_STAGE U

JOIN CUSTOMER_HYBRID_DIM OLD
    ON U.CUSTOMER_ID = OLD.CUSTOMER_ID

WHERE OLD.IS_CURRENT = FALSE

  AND OLD.EFFECTIVE_DATE = (
      SELECT MAX(X.EFFECTIVE_DATE)
      FROM CUSTOMER_HYBRID_DIM X
      WHERE X.CUSTOMER_ID = U.CUSTOMER_ID
  );

UPDATE CUSTOMER_HYBRID_DIM D
SET
    CUSTOMER_NAME = U.CUSTOMER_NAME,

    CITY = U.CITY,

    STATE = U.STATE,

    CURRENT_MEMBERSHIP = U.MEMBERSHIP,

    PREVIOUS_MEMBERSHIP =
        CASE
            WHEN D.CUSTOMER_ID = U.CUSTOMER_ID
            THEN U_PREV.CURRENT_MEMBERSHIP
            ELSE D.PREVIOUS_MEMBERSHIP
        END

FROM CUSTOMER_UPDATES_STAGE U

JOIN CUSTOMER_HYBRID_DIM U_PREV
    ON U.CUSTOMER_ID = U_PREV.CUSTOMER_ID

WHERE D.CUSTOMER_ID = U.CUSTOMER_ID

  AND U_PREV.EFFECTIVE_DATE = (
      SELECT MAX(X.EFFECTIVE_DATE)
      FROM CUSTOMER_HYBRID_DIM X
      WHERE X.CUSTOMER_ID = U.CUSTOMER_ID
  );

UPDATE CUSTOMER_HYBRID_DIM D
SET
    CUSTOMER_NAME = U.CUSTOMER_NAME,
    CITY = U.CITY,
    STATE = U.STATE,
    CURRENT_MEMBERSHIP = U.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = OLD.CURRENT_MEMBERSHIP
FROM CUSTOMER_UPDATES_STAGE U
JOIN CUSTOMER_HYBRID_DIM OLD
    ON U.CUSTOMER_ID = OLD.CUSTOMER_ID
WHERE D.CUSTOMER_ID = U.CUSTOMER_ID
  AND OLD.IS_CURRENT = FALSE
  AND OLD.EFFECTIVE_DATE = (
      SELECT MAX(X.EFFECTIVE_DATE)
      FROM CUSTOMER_HYBRID_DIM X
      WHERE X.CUSTOMER_ID = U.CUSTOMER_ID
        AND X.IS_CURRENT = FALSE
  );

CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_UPDATE_CONTEXT AS
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY AS NEW_CITY,
    U.STATE AS NEW_STATE,
    U.MEMBERSHIP AS NEW_MEMBERSHIP,
    U.SEGMENT AS NEW_SEGMENT,
    U.EFFECTIVE_DATE,

    D.CITY AS OLD_CITY,
    D.STATE AS OLD_STATE,
    D.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,
    D.SEGMENT AS OLD_SEGMENT

FROM CUSTOMER_UPDATES_STAGE U

JOIN CUSTOMER_HYBRID_DIM D
    ON U.CUSTOMER_ID = D.CUSTOMER_ID

WHERE D.IS_CURRENT = TRUE;

SELECT *
FROM CUSTOMER_UPDATE_CONTEXT
ORDER BY CUSTOMER_ID;

UPDATE CUSTOMER_HYBRID_DIM D
SET
    EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        C.EFFECTIVE_DATE
    ),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATE_CONTEXT C
WHERE D.CUSTOMER_ID = C.CUSTOMER_ID
  AND D.IS_CURRENT = TRUE;

INSERT INTO CUSTOMER_HYBRID_DIM
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,

    CUSTOMER_NAME,

    NEW_CITY,

    OLD_CITY AS PREVIOUS_CITY,

    NEW_STATE,

    NEW_MEMBERSHIP AS CURRENT_MEMBERSHIP,

    OLD_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    NEW_MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    NEW_SEGMENT AS SEGMENT,

    EFFECTIVE_DATE,

    '9999-12-31'::DATE,

    TRUE

FROM CUSTOMER_UPDATE_CONTEXT;

UPDATE CUSTOMER_HYBRID_DIM D
SET
    CUSTOMER_NAME = C.CUSTOMER_NAME,

    CITY = C.NEW_CITY,

    STATE = C.NEW_STATE,

    CURRENT_MEMBERSHIP = C.NEW_MEMBERSHIP,

    PREVIOUS_MEMBERSHIP = C.OLD_MEMBERSHIP

FROM CUSTOMER_UPDATE_CONTEXT C

WHERE D.CUSTOMER_ID = C.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_HYBRID_DIM
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM CUSTOMER_HYBRID_DIM
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM CUSTOMER_HYBRID_DIM
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE >= EFFECTIVE_DATE
  AND '2026-03-15'::DATE <= EXPIRY_DATE;

