CREATE WAREHOUSE IF NOT EXISTS SCD_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE SCD_WH;

CREATE DATABASE IF NOT EXISTS CUSTOMER_HISTORY_DB;

USE DATABASE CUSTOMER_HISTORY_DB;

CREATE SCHEMA IF NOT EXISTS CUSTOMER_HISTORY_SCHEMA;

USE SCHEMA CUSTOMER_HISTORY_SCHEMA;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

LIST @CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

COPY INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;

SELECT
    D.CUSTOMER_ID,

    D.CITY AS OLD_CITY,
    U.CITY AS NEW_CITY,

    D.MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP

FROM DIM_CUSTOMER D

INNER JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID

WHERE
       D.CITY <> U.CITY
    OR D.STATE <> U.STATE
    OR D.MEMBERSHIP <> U.MEMBERSHIP
    OR D.SEGMENT <> U.SEGMENT

ORDER BY D.CUSTOMER_ID;

SELECT
    D.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    D.CITY AS OLD_VALUE,
    U.CITY AS NEW_VALUE

FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID

WHERE D.CITY <> U.CITY


UNION ALL


-- STATE CHANGES

SELECT
    D.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    D.STATE AS OLD_VALUE,
    U.STATE AS NEW_VALUE

FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID

WHERE D.STATE <> U.STATE


UNION ALL


-- MEMBERSHIP CHANGES

SELECT
    D.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    D.MEMBERSHIP AS OLD_VALUE,
    U.MEMBERSHIP AS NEW_VALUE

FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID

WHERE D.MEMBERSHIP <> U.MEMBERSHIP


UNION ALL


-- SEGMENT CHANGES

SELECT
    D.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    D.SEGMENT AS OLD_VALUE,
    U.SEGMENT AS NEW_VALUE

FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID

WHERE D.SEGMENT <> U.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;


UPDATE DIM_CUSTOMER D

SET
    CITY = U.CITY,
    STATE = U.STATE,
    MEMBERSHIP = U.MEMBERSHIP,
    SEGMENT = U.SEGMENT

FROM CUSTOMER_UPDATES U

WHERE D.CUSTOMER_ID = U.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT

FROM DIM_CUSTOMER

ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP

FROM DIM_CUSTOMER

WHERE CUSTOMER_ID = 101;

