CREATE WAREHOUSE IF NOT EXISTS project13
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
USE WAREHOUSE project13;
CREATE DATABASE IF NOT EXISTS RETAIL_SCHEMAS_DW;

USE DATABASE RETAIL_SCHEMAS_DW;

CREATE SCHEMA IF NOT EXISTS SCHEMA_COMPARISON;

USE SCHEMA SCHEMA_COMPARISON;
CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;

list @retail_stage;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

SHOW STAGES;

LIST @RETAIL_STAGE;

CREATE OR REPLACE TABLE STAR_DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);
CREATE OR REPLACE TABLE STAR_DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);
INSERT INTO STAR_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT
    $1::NUMBER,
    $2::VARCHAR,
    $3::VARCHAR,
    $4::VARCHAR,
    $5::VARCHAR,
    $6::VARCHAR
FROM @RETAIL_STAGE/regions_and_stores.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);
INSERT INTO STAR_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    $1::NUMBER,
    $2::VARCHAR,
    $3::VARCHAR,
    $4::VARCHAR,
    $5::NUMBER(10,2)
FROM @RETAIL_STAGE/product_hierarchy.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);
LIST @RETAIL_STAGE;
INSERT INTO STAR_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    $1::NUMBER,
    $2::VARCHAR,
    $3::VARCHAR,
    $4::VARCHAR,
    $5::NUMBER(10,2)
FROM @RETAIL_STAGE/product_hierarchy.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);

CREATE OR REPLACE TABLE STAR_FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (STORE_KEY)
        REFERENCES STAR_DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO STAR_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    t.$1::VARCHAR,
    t.$2::DATE,
    t.$3::NUMBER,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.$6::NUMBER,
    t.$6::NUMBER * t.$7::NUMBER(10,2)
FROM @RETAIL_STAGE/sales_transactions.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
) t
JOIN STAR_DIM_STORE s
    ON s.STORE_ID = t.$4::NUMBER
JOIN STAR_DIM_PRODUCT p
    ON p.PRODUCT_ID = t.$5::NUMBER;

CREATE OR REPLACE TABLE SNOW_DIM_REGION
(
    REGION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);
CREATE OR REPLACE TABLE SNOW_DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_KEY NUMBER,

    FOREIGN KEY (REGION_KEY)
        REFERENCES SNOW_DIM_REGION(REGION_KEY)
);
CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY
(
    CATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);
CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY NUMBER,

    FOREIGN KEY (CATEGORY_KEY)
        REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);
CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER,

    FOREIGN KEY (SUBCATEGORY_KEY)
        REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);
INSERT INTO SNOW_DIM_REGION
(
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT DISTINCT
    $5::VARCHAR,
    $6::VARCHAR
FROM @RETAIL_STAGE/regions_and_stores.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);

INSERT INTO SNOW_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    t.$1::NUMBER,
    t.$2::VARCHAR,
    t.$3::VARCHAR,
    t.$4::VARCHAR,
    r.REGION_KEY
FROM @RETAIL_STAGE/regions_and_stores.csv t
JOIN SNOW_DIM_REGION r
    ON r.REGION_NAME = t.$5::VARCHAR
   AND r.REGIONAL_MANAGER = t.$6::VARCHAR
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);

SELECT * FROM SNOW_DIM_REGION;
INSERT INTO SNOW_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    t.STORE_ID,
    t.STORE_NAME,
    t.CITY,
    t.STATE,
    r.REGION_KEY
FROM
(
    SELECT
        $1::NUMBER AS STORE_ID,
        $2::VARCHAR AS STORE_NAME,
        $3::VARCHAR AS CITY,
        $4::VARCHAR AS STATE,
        $5::VARCHAR AS REGION_NAME,
        $6::VARCHAR AS REGIONAL_MANAGER
    FROM @RETAIL_STAGE/regions_and_stores.csv
    (
        FILE_FORMAT => 'RETAIL_CSV_FORMAT'
    )
) t
JOIN SNOW_DIM_REGION r
    ON t.REGION_NAME = r.REGION_NAME
   AND t.REGIONAL_MANAGER = r.REGIONAL_MANAGER;

INSERT INTO SNOW_DIM_CATEGORY
(
    CATEGORY_NAME
)
SELECT DISTINCT
    $4::VARCHAR
FROM @RETAIL_STAGE/product_hierarchy.csv
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
);

INSERT INTO SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT DISTINCT
    p.SUBCATEGORY_NAME,
    c.CATEGORY_KEY
FROM
(
    SELECT
        $3::VARCHAR AS SUBCATEGORY_NAME,
        $4::VARCHAR AS CATEGORY_NAME
    FROM @RETAIL_STAGE/product_hierarchy.csv
    (FILE_FORMAT => 'RETAIL_CSV_FORMAT')
) p
JOIN SNOW_DIM_CATEGORY c
    ON c.CATEGORY_NAME = p.CATEGORY_NAME;

CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER,
    FOREIGN KEY (SUBCATEGORY_KEY)
        REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);

INSERT INTO SNOW_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    s.SUBCATEGORY_KEY
FROM
(
    SELECT
        $1::NUMBER AS PRODUCT_ID,
        $2::VARCHAR AS PRODUCT_NAME,
        $3::VARCHAR AS SUBCATEGORY_NAME,
        $4::VARCHAR AS CATEGORY_NAME,
        $5::NUMBER(10,2) AS UNIT_PRICE
    FROM @RETAIL_STAGE/product_hierarchy.csv
    (FILE_FORMAT => 'RETAIL_CSV_FORMAT')
) p
JOIN SNOW_DIM_SUBCATEGORY s
    ON s.SUBCATEGORY_NAME = p.SUBCATEGORY_NAME;

CREATE OR REPLACE TABLE SNOW_FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (STORE_KEY)
        REFERENCES SNOW_DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY)
);
INSERT INTO SNOW_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_DATE,
    t.CUSTOMER_ID,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.QUANTITY,
    t.QUANTITY * t.UNIT_PRICE
FROM
(
    SELECT
        $1::VARCHAR AS TRANSACTION_ID,
        $2::DATE AS TRANSACTION_DATE,
        $3::NUMBER AS CUSTOMER_ID,
        $4::NUMBER AS STORE_ID,
        $5::NUMBER AS PRODUCT_ID,
        $6::NUMBER AS QUANTITY,
        $7::NUMBER(10,2) AS UNIT_PRICE
    FROM @RETAIL_STAGE/sales_transactions.csv
    (FILE_FORMAT => 'RETAIL_CSV_FORMAT')
) t
JOIN SNOW_DIM_STORE s
    ON s.STORE_ID = t.STORE_ID
JOIN SNOW_DIM_PRODUCT p
    ON p.PRODUCT_ID = t.PRODUCT_ID;

SELECT
    s.REGION_NAME,
    p.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN STAR_DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
GROUP BY
    s.REGION_NAME,
    p.CATEGORY_NAME
ORDER BY
    s.REGION_NAME,
    p.CATEGORY_NAME;

SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f

JOIN SNOW_DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY

JOIN SNOW_DIM_REGION r
    ON s.REGION_KEY = r.REGION_KEY

JOIN SNOW_DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY

JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY

JOIN SNOW_DIM_CATEGORY c
    ON sc.CATEGORY_KEY = c.CATEGORY_KEY

GROUP BY
    r.REGION_NAME,
    c.CATEGORY_NAME

ORDER BY
    r.REGION_NAME,
    c.CATEGORY_NAME;

SELECT
    r.REGIONAL_MANAGER,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f
JOIN SNOW_DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN SNOW_DIM_REGION r
    ON s.REGION_KEY = r.REGION_KEY
GROUP BY
    r.REGIONAL_MANAGER
ORDER BY
    r.REGIONAL_MANAGER;

SELECT 'STAR_DIM_STORE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT 'STAR_DIM_PRODUCT', COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT 'STAR_FACT_SALES', COUNT(*)
FROM STAR_FACT_SALES;

SELECT 'SNOW_DIM_REGION' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM SNOW_DIM_REGION

UNION ALL

SELECT 'SNOW_DIM_STORE', COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT 'SNOW_DIM_CATEGORY', COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT 'SNOW_DIM_SUBCATEGORY', COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT 'SNOW_DIM_PRODUCT', COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT 'SNOW_FACT_SALES', COUNT(*)
FROM SNOW_FACT_SALES;

