CREATE WAREHOUSE IF NOT EXISTS RETAIL_DW_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
USE WAREHOUSE RETAIL_DW_WH;

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
USE DATABASE RETAIL_DW;

CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS;
USE SCHEMA SALES_ANALYTICS;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '');
CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = RETAIL_CSV_FORMAT;

LIST @RETAIL_STAGE;

CREATE OR REPLACE TABLE STG_STORES
(
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);
CREATE OR REPLACE TABLE STG_PRODUCTS
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);
CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);
CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

COPY INTO STG_STORES
FROM @RETAIL_STAGE/stores.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_CUSTOMERS_INITIAL
FROM @RETAIL_STAGE/customers_initial.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_CUSTOMER_UPDATES
FROM @RETAIL_STAGE/customer_updates.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'STORES' AS SOURCE, COUNT(*) AS RECORD_COUNT
FROM STG_STORES

UNION ALL

SELECT 'PRODUCTS', COUNT(*)
FROM STG_PRODUCTS

UNION ALL

SELECT 'INITIAL CUSTOMERS', COUNT(*)
FROM STG_CUSTOMERS_INITIAL

UNION ALL

SELECT 'CUSTOMER UPDATES', COUNT(*)
FROM STG_CUSTOMER_UPDATES;

CREATE OR REPLACE TABLE DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1
        PRIMARY KEY,

    STORE_ID NUMBER NOT NULL,

    STORE_NAME VARCHAR(100),

    CITY VARCHAR(50),

    STATE VARCHAR(50),

    STORE_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1
        PRIMARY KEY,

    PRODUCT_ID NUMBER NOT NULL,

    PRODUCT_NAME VARCHAR(100),

    CATEGORY VARCHAR(50),

    UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1
        PRIMARY KEY,

    CUSTOMER_ID NUMBER NOT NULL,

    CUSTOMER_NAME VARCHAR(100),

    CITY VARCHAR(50),

    PREVIOUS_CITY VARCHAR(50),

    STATE VARCHAR(50),

    CURRENT_MEMBERSHIP VARCHAR(30),

    PREVIOUS_MEMBERSHIP VARCHAR(30),

    HISTORICAL_MEMBERSHIP VARCHAR(30),

    SEGMENT VARCHAR(30),

    EFFECTIVE_DATE DATE,

    EXPIRY_DATE DATE,

    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM STG_STORES;

INSERT INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM STG_PRODUCTS;

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,

    CUSTOMER_NAME,

    CITY,

    NULL AS PREVIOUS_CITY,

    STATE,

    MEMBERSHIP AS CURRENT_MEMBERSHIP,

    NULL AS PREVIOUS_MEMBERSHIP,

    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    SEGMENT,

    '2026-01-01'::DATE,

    '9999-12-31'::DATE,

    TRUE

FROM STG_CUSTOMERS_INITIAL;

CREATE OR REPLACE TABLE FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1
        PRIMARY KEY,

    TRANSACTION_ID VARCHAR(50),

    TRANSACTION_DATE DATE,

    CUSTOMER_KEY NUMBER,

    STORE_KEY NUMBER,

    PRODUCT_KEY NUMBER,

    QUANTITY NUMBER,

    UNIT_PRICE NUMBER(10,2),

    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_FACT_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    CONSTRAINT FK_FACT_STORE
        FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    CONSTRAINT FK_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15'::DATE,

    C.CUSTOMER_KEY,

    S.STORE_KEY,

    P.PRODUCT_KEY,

    1,

    P.UNIT_PRICE,

    1 * P.UNIT_PRICE

FROM DIM_CUSTOMER_HYBRID C

JOIN DIM_STORE S
    ON S.STORE_ID = 201

JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 501

WHERE C.CUSTOMER_ID = 101

  AND '2026-02-15'::DATE
      BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE;

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10'::DATE,

    C.CUSTOMER_KEY,

    S.STORE_KEY,

    P.PRODUCT_KEY,

    2,

    P.UNIT_PRICE,

    2 * P.UNIT_PRICE

FROM DIM_CUSTOMER_HYBRID C

JOIN DIM_STORE S
    ON S.STORE_ID = 203

JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 502

WHERE C.CUSTOMER_ID = 103

  AND '2026-03-10'::DATE
      BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE;

UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_UPDATE_CONTEXT AS
SELECT
    U.CUSTOMER_ID,

    U.CUSTOMER_NAME,

    U.CITY AS NEW_CITY,

    U.STATE AS NEW_STATE,

    U.MEMBERSHIP AS NEW_MEMBERSHIP,

    U.SEGMENT AS NEW_SEGMENT,

    U.EFFECTIVE_DATE,

    D.CITY AS OLD_CITY,

    D.STATE AS OLD_STATE,

    D.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,

    D.SEGMENT AS OLD_SEGMENT

FROM STG_CUSTOMER_UPDATES U

JOIN DIM_CUSTOMER_HYBRID D
    ON U.CUSTOMER_ID = D.CUSTOMER_ID

WHERE D.IS_CURRENT = TRUE;

SELECT *
FROM CUSTOMER_UPDATE_CONTEXT
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID D
SET
    EXPIRY_DATE = DATEADD(
        DAY,
        -1,
        C.EFFECTIVE_DATE
    ),

    IS_CURRENT = FALSE

FROM CUSTOMER_UPDATE_CONTEXT C

WHERE D.CUSTOMER_ID = C.CUSTOMER_ID
  AND D.IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,

    CUSTOMER_NAME,

    NEW_CITY,

    OLD_CITY AS PREVIOUS_CITY,

    NEW_STATE,

    NEW_MEMBERSHIP AS CURRENT_MEMBERSHIP,

    OLD_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    NEW_MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    NEW_SEGMENT AS SEGMENT,

    EFFECTIVE_DATE,

    '9999-12-31'::DATE,

    TRUE

FROM CUSTOMER_UPDATE_CONTEXT;

UPDATE DIM_CUSTOMER_HYBRID D
SET
    CUSTOMER_NAME = C.CUSTOMER_NAME,

    CITY = C.NEW_CITY,

    STATE = C.NEW_STATE,

    CURRENT_MEMBERSHIP = C.NEW_MEMBERSHIP,

    PREVIOUS_MEMBERSHIP = C.OLD_MEMBERSHIP

FROM CUSTOMER_UPDATE_CONTEXT C

WHERE D.CUSTOMER_ID = C.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',

    '2026-04-15'::DATE,

    C.CUSTOMER_KEY,

    S.STORE_KEY,

    P.PRODUCT_KEY,

    1,

    P.UNIT_PRICE,

    1 * P.UNIT_PRICE

FROM DIM_CUSTOMER_HYBRID C

JOIN DIM_STORE S
    ON S.STORE_ID = 201

JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 503

WHERE C.CUSTOMER_ID = 101

  AND C.IS_CURRENT = TRUE;

SELECT
    SALES_KEY,
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
FROM FACT_SALES
ORDER BY TRANSACTION_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    F.TRANSACTION_ID,

    F.TRANSACTION_DATE,

    C.CUSTOMER_ID,

    C.CUSTOMER_NAME,

    C.CITY AS CURRENT_CITY,

    C.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,

    C.SEGMENT AS SEGMENT_AT_PURCHASE,

    S.STORE_NAME,

    P.PRODUCT_NAME,

    F.TOTAL_AMOUNT

FROM FACT_SALES F

JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY

JOIN DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY

JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY

WHERE C.CUSTOMER_ID = 101

ORDER BY F.TRANSACTION_DATE;

SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM FACT_SALES;

