create warehouse if not exists HEALTHCARE_WH
warehouse_size = 'xsmall'
auto_suspend = 60
auto_resume = TRUE;

use warehouse HEALTHCARE_WH;

create database if not exists HEALTHCARE_DB;
USE database HEALTHCARE_DB;

create schema if not exists HEALTHCARE_SCHEMA;
USE SCHEMA HEALTHCARE_SCHEMA;

CREATE OR REPLACE FILE FORMAT HEALTHCARE_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'YYYY-MM-DD'
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
FILE_FORMAT = HEALTHCARE_CSV_FORMAT;

LIST @HEALTHCARE_STAGE;

create table if not exists dim_patient(patient_key number autoincrement start 1 increment 1,patient_id varchar(20),patient_name varchar(20),gender varchar(30),city varchar(30),state varchar(30),constraint pk_dim_patient primary key(patient_key));

create or replace table dim_doctor(doctor_key number autoincrement start 1 increment 1,doctor_id varchar(20),doctor_name varchar(30),specialization varchar(40),constraint pk_dim_doctor primary key(doctor_key));

create or replace table dim_hospitals(hospital_key number autoincrement start 1 increment 1,hospital_id varchar(30),hospital_name varchar(30),city varchar(30),state varchar(30),region varchar(30), constraint pk_dim_hospital primary key(hospital_key));

CREATE OR REPLACE TABLE DIM_DEPARTMENT
(
    DEPARTMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100),

    CONSTRAINT PK_DIM_DEPARTMENT
        PRIMARY KEY (DEPARTMENT_KEY)
);

CREATE OR REPLACE TABLE DIM_TREATMENT
(
    TREATMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100),

    CONSTRAINT PK_DIM_TREATMENT
        PRIMARY KEY (TREATMENT_KEY)
);

CREATE OR REPLACE TABLE STG_PATIENT
(
    PATIENT_ID VARCHAR(20),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_DOCTOR
(
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_HOSPITAL
(
    HOSPITAL_ID VARCHAR(20),
    HOSPITAL_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_DEPARTMENT
(
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_TREATMENT
(
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100)
);

COPY INTO STG_PATIENT
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

SELECT
    $1 AS PATIENT_ID,
    $2 AS PATIENT_NAME,
    $3 AS GENDER,
    $4 AS CITY,
    $5 AS STATE
FROM @HEALTHCARE_STAGE/patients.csv
(FILE_FORMAT => 'HEALTHCARE_CSV_FORMAT');

CREATE OR REPLACE FILE FORMAT HEALTHCARE_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
SKIP_BLANK_LINES = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

COPY INTO STG_PATIENT
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

INSERT INTO DIM_PATIENT
(
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
)
SELECT
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
FROM STG_PATIENT;

COPY INTO STG_DOCTOR
FROM @HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';
INSERT INTO DIM_DOCTOR
(
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
)
SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM STG_DOCTOR;

COPY INTO STG_HOSPITAL
FROM @HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

INSERT INTO DIM_HOSPITALS
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
FROM STG_HOSPITAL;

COPY INTO STG_DEPARTMENT
FROM @HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';
INSERT INTO DIM_DEPARTMENT
(
    DEPARTMENT_ID,
    DEPARTMENT_NAME
)
SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM STG_DEPARTMENT;

COPY INTO STG_TREATMENT
FROM @HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';
INSERT INTO DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
FROM STG_TREATMENT;

SELECT 'PATIENT' AS DIMENSION, COUNT(*) AS RECORD_COUNT
FROM DIM_PATIENT

UNION ALL

SELECT 'DOCTOR', COUNT(*)
FROM DIM_DOCTOR

UNION ALL

SELECT 'HOSPITAL', COUNT(*)
FROM DIM_HOSPITALS

UNION ALL

SELECT 'DEPARTMENT', COUNT(*)
FROM DIM_DEPARTMENT

UNION ALL

SELECT 'TREATMENT', COUNT(*)
FROM DIM_TREATMENT;

select * from dim_doctor;

CREATE OR REPLACE TABLE DIM_DOCTOR
(
    DOCTOR_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);
INSERT INTO DIM_DOCTOR
(
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
)
SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM STG_DOCTOR;

select * from dim_doctor;

CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,

    CONSTRAINT PK_DIM_DATE
        PRIMARY KEY (DATE_KEY)
);
INSERT INTO DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY,
    DAYNAME(DATE_VALUE) AS DAY_NAME,
    WEEK(DATE_VALUE) AS WEEK_NO,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    'Q' || QUARTER(DATE_VALUE) AS QUARTER,
    YEAR(DATE_VALUE) AS YEAR
FROM
(
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            '2026-01-01'::DATE
        ) AS DATE_VALUE
    FROM TABLE(
        GENERATOR(ROWCOUNT => 90)
    )
);

CREATE OR REPLACE TABLE FACT_ADMISSION
(
    ADMISSION_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    PATIENT_KEY NUMBER,
    DOCTOR_KEY NUMBER,
    HOSPITAL_KEY NUMBER,
    DEPARTMENT_KEY NUMBER,
    DATE_KEY NUMBER,

    ADMISSION_COUNT NUMBER,
    LENGTH_OF_STAY NUMBER,

    CONSTRAINT PK_FACT_ADMISSION
        PRIMARY KEY (ADMISSION_KEY)
);
CREATE OR REPLACE TABLE STG_ADMISSION
(
    ADMISSION_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    DOCTOR_ID VARCHAR(20),
    HOSPITAL_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);
COPY INTO STG_ADMISSION
FROM @HEALTHCARE_STAGE/admissions.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';
INSERT INTO FACT_ADMISSION
(
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    DATE_KEY,
    ADMISSION_COUNT,
    LENGTH_OF_STAY
)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    DT.DATE_KEY,

    1 AS ADMISSION_COUNT,

    DATEDIFF(
        DAY,
        A.ADMISSION_DATE,
        A.DISCHARGE_DATE
    ) AS LENGTH_OF_STAY

FROM STG_ADMISSION A

JOIN DIM_PATIENT P
    ON A.PATIENT_ID = P.PATIENT_ID

JOIN DIM_DOCTOR D
    ON A.DOCTOR_ID = D.DOCTOR_ID

JOIN DIM_HOSPITALS H
    ON A.HOSPITAL_ID = H.HOSPITAL_ID

JOIN DIM_DEPARTMENT DP
    ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID

JOIN DIM_DATE DT
    ON A.ADMISSION_DATE = DT.FULL_DATE;

    CREATE OR REPLACE TABLE FACT_BILLING
(
    BILLING_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    PATIENT_KEY NUMBER,
    DOCTOR_KEY NUMBER,
    HOSPITAL_KEY NUMBER,
    DEPARTMENT_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    DATE_KEY NUMBER,

    QUANTITY NUMBER,
    TREATMENT_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(12,2),
    NET_AMOUNT NUMBER(12,2),

    CONSTRAINT PK_FACT_BILLING
        PRIMARY KEY (BILLING_KEY)
);

CREATE OR REPLACE TABLE STG_BILLING
(
    ADMISSION_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    DOCTOR_ID VARCHAR(20),
    HOSPITAL_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    TREATMENT_ID VARCHAR(20),
    BILLING_DATE DATE,
    QUANTITY NUMBER,
    TREATMENT_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(12,2)
);
COPY INTO STG_BILLING
FROM @HEALTHCARE_STAGE/billing.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHCARE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

INSERT INTO FACT_BILLING
(
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    TREATMENT_KEY,
    DATE_KEY,
    QUANTITY,
    TREATMENT_AMOUNT,
    DISCOUNT,
    NET_AMOUNT
)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    T.TREATMENT_KEY,
    DT.DATE_KEY,

    B.QUANTITY,

    B.TREATMENT_AMOUNT,

    B.DISCOUNT,

    B.TREATMENT_AMOUNT - B.DISCOUNT AS NET_AMOUNT

FROM STG_BILLING B

JOIN DIM_PATIENT P
    ON B.PATIENT_ID = P.PATIENT_ID

JOIN DIM_DOCTOR D
    ON B.DOCTOR_ID = D.DOCTOR_ID

JOIN DIM_HOSPITALS H
    ON B.HOSPITAL_ID = H.HOSPITAL_ID

JOIN DIM_DEPARTMENT DP
    ON B.DEPARTMENT_ID = DP.DEPARTMENT_ID

JOIN DIM_TREATMENT T
    ON B.TREATMENT_ID = T.TREATMENT_ID

JOIN DIM_DATE DT
    ON B.BILLING_DATE = DT.FULL_DATE;


select h.hospital_name,sum(a.admission_count) as TOTAL_ADMISSIONS
from fact_admission a
join dim_hospitals h
on h.hospital_key = a.hospital_key
group by h.hospital_name

select h.hospital_name,sum(f.net_amount) as total_revenue
from dim_hospitals h 
join fact_billing f
on h.hospital_key=f.hospital_key

select to_char(d.full_date,'YYYY-MM') as month,sum(f.net_amount) as total_revenue
from fact_billing f
join dim_date d
on f.date_key=d.date_key
group by to_char(d.full_date,'YYYY-MM')

SELECT
    h.hospital_name,
    SUM(a.admission_count) AS total_admissions
FROM FACT_ADMISSION AS a
JOIN DIM_HOSPITALS AS h
    ON a.hospital_key = h.hospital_key
GROUP BY
    h.hospital_name
ORDER BY
    total_admissions DESC;


SELECT
    h.hospital_name,
    SUM(f.net_amount) AS total_revenue
FROM FACT_BILLING AS f
JOIN DIM_HOSPITALS AS h
    ON f.hospital_key = h.hospital_key
GROUP BY
    h.hospital_name
ORDER BY
    total_revenue DESC;

SELECT
    d.doctor_name,
    SUM(f.net_amount) AS total_revenue
FROM FACT_BILLING AS f
JOIN DIM_DOCTOR AS d
    ON f.doctor_key = d.doctor_key
GROUP BY
    d.doctor_name
ORDER BY
    total_revenue DESC;

