CREATE WAREHOUSE IF NOT EXISTS CUSTOMER_SCD_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE CUSTOMER_SCD_WH;

CREATE DATABASE IF NOT EXISTS CUSTOMER_SCD_DB;

USE DATABASE CUSTOMER_SCD_DB;

CREATE SCHEMA IF NOT EXISTS CUSTOMER_SCD_SCHEMA;

USE SCHEMA CUSTOMER_SCD_SCHEMA;

create or replace table customer_initial (
customer_id number,
customer_name varchar(40),
city varchar(30),
state varchar(30),
membership varchar(30),
segment varchar(30)
);

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE CUSTOMER_SCD_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_SCD_STAGE;

COPY INTO CUSTOMER_INITIAL
FROM @CUSTOMER_SCD_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

COPY INTO CUSTOMER_INITIAL
FROM @CUSTOMER_SCD_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

REMOVE @CUSTOMER_SCD_STAGE/customers_initial.csv;

COPY INTO CUSTOMER_INITIAL
FROM @CUSTOMER_SCD_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_SCD_STAGE/customer_updates.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

INSERT INTO DIM_CUSTOMER_TYPE1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM CUSTOMER_INITIAL;

SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE1 d
SET
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

SELECT *
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_INITIAL;

UPDATE DIM_CUSTOMER_TYPE2 d
SET
    EXPIRY_DATE = DATEADD(day, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;

SELECT *
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES;

SELECT *
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT *
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT *
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;