CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
create database if not exists RETAIL_DB;
use RETAIL_DB;
create schema if not exists SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

CREATE FILE FORMAT IF NOT EXISTS RETAIL_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;

SHOW STAGES;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    MEMBERSHIP VARCHAR(20)
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100)
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    QUANTITY NUMBER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
);

COPY INTO PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
);

COPY INTO BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
);

COPY INTO SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
);

SELECT * FROM CUSTOMERS;

SELECT * FROM PRODUCTS;

SELECT * FROM BRANCHES;

SELECT * FROM SALES;

select c.CUSTOMER_ID,c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING
    from CUSTOMERS c
    join Sales s
    on c.CUSTOMER_ID = s.customer_id
    group by c.customer_name,c.customer_id
    order by TOTAL_SPENDING desc;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES b
JOIN SALES s
    ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS p
JOIN SALES s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.CATEGORY,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS p
JOIN SALES s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES b
JOIN SALES s
    ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS p
JOIN SALES s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

select customer_name,total_spending,rank() over (order by total_spending desc) as CUSTOMER_RANK
from (select c.customer_name,sum(s.total_amount) as total_spending  
from customers c join sales s on c.customer_id=s.customer_id group by c.customer_name);

SELECT
    BRANCH_NAME,
    TOTAL_SALES,
    RANK() OVER (
        ORDER BY TOTAL_SALES DESC
    ) AS BRANCH_RANK
FROM (
    SELECT
        B.BRANCH_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
    FROM BRANCHES B
    JOIN SALES S
        ON B.BRANCH_ID = S.BRANCH_ID
    GROUP BY B.BRANCH_NAME
);

WITH PRODUCT_SALES AS (
    SELECT
        P.CATEGORY,
        P.PRODUCT_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM PRODUCTS P
    JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.CATEGORY,
        P.PRODUCT_NAME
),

RANKED_PRODUCTS AS (
    SELECT
        CATEGORY,
        PRODUCT_NAME,
        TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS RN
    FROM PRODUCT_SALES
)

SELECT
    CATEGORY,
    PRODUCT_NAME,
    TOTAL_REVENUE
FROM RANKED_PRODUCTS
WHERE RN = 1;

select sale_date,sale_id,total_amount, sum(total_amount) over(order by total_amount desc) as CUMULATIVE_SALES
from sales
order by sale_date;

select sale_date,sale_id,total_amount, avg(total_amount) over(order by total_amount desc) as AVERAGE_SALES
from sales
order by sale_date;

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
),

AVERAGE_SPENDING AS (
    SELECT
        AVG(TOTAL_SPENDING) AS AVG_SPENDING
    FROM CUSTOMER_REVENUE
)

SELECT
    CR.CUSTOMER_ID,
    CR.CUSTOMER_NAME,
    CR.TOTAL_SPENDING
FROM CUSTOMER_REVENUE CR
CROSS JOIN AVERAGE_SPENDING A
WHERE CR.TOTAL_SPENDING > A.AVG_SPENDING
ORDER BY CR.TOTAL_SPENDING DESC;

CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE,

    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,

    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,

    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,

    S.QUANTITY,
    P.PRICE,
    S.TOTAL_AMOUNT

FROM SALES S
JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;
SELECT *
FROM SALES_REPORT
ORDER BY SALE_ID;

CREATE OR REPLACE  VIEW TOP_CUSTOMERS AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;
select * FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC;