USE WAREHOUSE ENTERPRISE_WH;

USE DATABASE ENTERPRISE_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null');

SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS MEMBERSHIP
FROM @RETAIL_STAGE/customers.csv
(FILE_FORMAT => 'RETAIL_CSV_FORMAT')
LIMIT 10;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);

CREATE OR REPLACE FILE FORMAT RETAIL_CUSTOMER_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_BLANK_LINES = TRUE
TRIM_SPACE = TRUE;

SHOW FILE FORMATS;
TRUNCATE TABLE DIM_CUSTOMER;
COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = RETAIL_CUSTOMER_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE FILE FORMAT RETAIL_PRODUCT_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_BLANK_LINES = TRUE
TRIM_SPACE = TRUE;

TRUNCATE TABLE DIM_PRODUCT;

COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = RETAIL_PRODUCT_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE FILE FORMAT RETAIL_BRANCH_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_BLANK_LINES = TRUE
TRIM_SPACE = TRUE;

TRUNCATE TABLE DIM_BRANCH;

COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = RETAIL_BRANCH_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE FILE FORMAT RETAIL_DATE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_BLANK_LINES = TRUE
TRIM_SPACE = TRUE;

TRUNCATE TABLE DIM_DATE;

COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calender.csv
FILE_FORMAT = RETAIL_DATE_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE FILE FORMAT RETAIL_SALES_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
SKIP_BLANK_LINES = TRUE
TRIM_SPACE = TRUE;

TRUNCATE TABLE FACT_SALES;

COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = RETAIL_SALES_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);

show tables;

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_BRANCH', COUNT(*)
FROM DIM_BRANCH

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;

SELECT
    f.SALE_ID,
    c.CUSTOMER_NAME,
    p.PRODUCT_NAME,
    p.CATEGORY,
    b.BRANCH_NAME,
    b.STATE,
    d.DATE,
    f.QUANTITY,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
ORDER BY f.SALE_ID
LIMIT 10;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.STATE,
    b.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.STATE,
    b.REGION
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.STATE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    d.YEAR,
    d.MONTH,
    SUM(f.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.MONTH
ORDER BY
    d.YEAR,
    d.MONTH;

SELECT
    d.YEAR,
    d.QUARTER,
    SUM(f.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.QUARTER
ORDER BY
    d.YEAR,
    d.QUARTER;

SELECT
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_NAME,
    p.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    b.BRANCH_NAME,
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_NAME,
    b.STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    d.DATE,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    d.DATE
ORDER BY
    c.CUSTOMER_ID,
    d.DATE;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    SUM(f.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.TOTAL_AMOUNT) AS AVG_SALE_AMOUNT
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND
ORDER BY
    TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION,
    SUM(f.QUANTITY) AS TOTAL_UNITS_SOLD,
    COUNT(DISTINCT f.SALE_ID) AS TOTAL_TRANSACTIONS,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.TOTAL_AMOUNT) AS AVG_TRANSACTION_VALUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION
ORDER BY
    TOTAL_REVENUE DESC;