CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_WH;

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
USE DATABASE RETAIL_DW;

CREATE SCHEMA IF NOT EXISTS RETAIL_SCHEMA;
USE SCHEMA RETAIL_SCHEMA;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'YYYY-MM-DD'
NULL_IF = ('NULL', 'null');

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;

LIST @RETAIL_STAGE;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);
COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_CSV_FORMAT
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);
COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);
COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER,
    DATE_VALUE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(5)
);
COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calender.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2)
);
COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';
SELECT * FROM FACT_SALES
ORDER BY SALE_ID;

SELECT COUNT(*) AS MISSING_CUSTOMERS
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

SELECT COUNT(*) AS INVALID_PRODUCTS
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;

SELECT COUNT(*) AS INVALID_BRANCHES
FROM FACT_SALES f
LEFT JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
WHERE b.BRANCH_ID IS NULL;

SELECT COUNT(*) AS INVALID_DATES
FROM FACT_SALES f
LEFT JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
WHERE d.DATE_ID IS NULL;

SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM FACT_SALES
LIMIT 10;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    d.YEAR,
    d.MONTH,
    SUM(f.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.MONTH
ORDER BY
    d.YEAR,
    MIN(d.DATE_VALUE);

SELECT
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.STATE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 10;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY REVENUE DESC
LIMIT 10;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(f.SALE_ID) AS PURCHASE_COUNT,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC;

SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    SUM(f.QUANTITY) AS UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND
ORDER BY REVENUE DESC;

SELECT
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION,
    COUNT(f.SALE_ID) AS TOTAL_TRANSACTIONS,
    SUM(f.QUANTITY) AS UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION
ORDER BY REVENUE DESC;

SELECT
    b.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(f.QUANTITY) AS TOTAL_UNITS
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.REGION
ORDER BY TOTAL_REVENUE DESC;

SELECT
    d.YEAR,
    d.QUARTER,
    SUM(f.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.QUARTER
ORDER BY
    d.YEAR,
    d.QUARTER;

SELECT
    d.DATE_VALUE,
    SUM(f.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.DATE_VALUE
ORDER BY d.DATE_VALUE;

WITH CUSTOMER_REVENUE AS
(
    SELECT
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        SUM(f.TOTAL_AMOUNT) AS REVENUE
    FROM FACT_SALES f
    JOIN DIM_CUSTOMER c
        ON f.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME
)

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    REVENUE,
    RANK() OVER (
        ORDER BY REVENUE DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMER_REVENUE
ORDER BY CUSTOMER_RANK;

WITH PRODUCT_REVENUE AS
(
    SELECT
        p.PRODUCT_ID,
        p.PRODUCT_NAME,
        SUM(f.TOTAL_AMOUNT) AS REVENUE
    FROM FACT_SALES f
    JOIN DIM_PRODUCT p
        ON f.PRODUCT_ID = p.PRODUCT_ID
    GROUP BY
        p.PRODUCT_ID,
        p.PRODUCT_NAME
)

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    REVENUE,
    RANK() OVER (
        ORDER BY REVENUE DESC
    ) AS PRODUCT_RANK
FROM PRODUCT_REVENUE
ORDER BY PRODUCT_RANK;

CREATE OR REPLACE VIEW BRANCH_REVENUE AS
SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.STATE,
    b.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.STATE,
    b.REGION;
SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;